export { default as Main } from './Main/Main'
export { default as Blinker } from './Blinker/Blinker'
export { default as Crunch } from './Crunch/Crunch'
export { default as Insta } from './Insta/Insta'
export { default as Cookierun } from './Cookie/Cookierun'
export { default as Papaya } from './Papaya/Papaya'